import type { DetectiveCase } from './detectiveTypes';

export const extraDetectiveCases: DetectiveCase[] = [
  {
    title: 'The Robot Controller', location: 'Innovation Lab', time: 'Thursday, 4:00–4:25 PM',
    image: '/images/detective/robot-controller.png',
    imageAlt: 'Robotics lab with an empty controller outline and orange filament caught on a chair',
    people: [
      { name: 'Maya', role: 'Team captain', statement: 'I locked the controller beside the robot at 4:00, then took the inventory sheet to our teacher.' },
      { name: 'Theo', role: '3D-printing lead', statement: 'I stayed in the library after class. I never returned to the lab.' },
      { name: 'Mr. Cole', role: 'Lab assistant', statement: 'At 4:20 I noticed somebody had left orange printer filament trailing near the workbench.' },
    ],
    scene: 'The robotics team’s only wireless controller disappeared shortly before a demonstration. The lab door locks automatically and records every access card.',
    clues: [
      'Maya’s inventory photo at 4:02 shows the controller on the bench.',
      'The door log records Theo’s access card entering at 4:18 and leaving at 4:21.',
      'Theo claims he never returned after class.',
      'Bright orange filament is snagged on the chair beside the empty controller spot.',
      'Theo was printing robot parts with the same unusual orange filament that afternoon.',
    ],
    question: 'Whose statement conflicts with the physical and digital evidence?',
    answers: ['Maya’s', 'Theo’s', 'Mr. Cole’s', 'Nobody’s'], correctAnswer: 1,
    explanation: 'Theo denied entering, but his access card opened the lab and his distinctive filament was left beside the missing controller.',
  },
  {
    title: 'The Vanished Crown', location: 'Grandview School Theater', time: 'Friday, 6:30–6:50 PM',
    image: '/images/detective/costume-crown.png',
    imageAlt: 'Backstage costume trunk with an empty crown space, silver glitter, and purple thread',
    people: [
      { name: 'Priya', role: 'Lead performer', statement: 'I wore my purple costume all evening, but I never went near the prop trunk.' },
      { name: 'Ava', role: 'Prop manager', statement: 'I locked the crown in its velvet space before rehearsal and kept the trunk key with me.' },
      { name: 'Noah', role: 'Lighting helper', statement: 'I saw a sparkling trail toward the dressing rooms while checking the floor lights.' },
    ],
    scene: 'The jeweled stage crown vanished from a locked prop trunk. The lock was still closed when the prop manager discovered the empty velvet space.',
    clues: [
      'The trunk lock is undamaged, but its loose rear hinge allows the lid to lift slightly.',
      'A trail of silver crown glitter leads toward the dressing rooms.',
      'Purple thread is caught on the loose hinge.',
      'Only one performer wore a purple costume during rehearsal.',
      'Priya’s dressing-room shelf has several specks of matching silver glitter.',
    ],
    question: 'Who most likely pulled the crown through the loose side of the trunk?',
    answers: ['Priya', 'Ava', 'Noah', 'The director'], correctAnswer: 0,
    explanation: 'The purple thread and silver glitter connect Priya’s costume and dressing area to the trunk and missing crown.',
  },
  {
    title: 'The Replica Compass', location: 'Harbor History Museum', time: 'Sunday, 5:00–5:30 PM',
    image: '/images/detective/museum-compass.png',
    imageAlt: 'Museum case containing a clean brass compass beside a larger circular dust mark and a white glove',
    people: [
      { name: 'Dr. Vale', role: 'Curator', statement: 'The original compass is 12 centimeters wide and has a dark patch on its lid.' },
      { name: 'Rin', role: 'Restoration intern', statement: 'I cleaned the gallery, but I did not open this display or handle any replica.' },
      { name: 'Marcus', role: 'Security guard', statement: 'The alarm was disabled once with an authorized restoration code at 5:12.' },
    ],
    scene: 'During closing inspection, the curator notices that the historic compass in its case looks different. The alarm never sounded and the glass is intact.',
    clues: [
      'The displayed compass is spotless and only 10 centimeters wide.',
      'A 12-centimeter circular dust outline remains on the display fabric.',
      'The case alarm log records the restoration-team code at 5:12 PM.',
      'A restoration glove was left beside the case.',
      'Workshop records show Rin made a 10-centimeter practice replica that week.',
    ],
    question: 'Who had the access and matching replica needed for the swap?',
    answers: ['Dr. Vale', 'Rin', 'Marcus', 'A visitor'], correctAnswer: 1,
    explanation: 'The restoration code, glove, and exact-size practice replica all point to Rin despite the denial.',
  },
  {
    title: 'The Hallway Blackout', location: 'Science Wing', time: 'Monday, 6:18 PM',
    image: '/images/detective/hallway-blackout.png',
    imageAlt: 'Dim science hallway with a lowered breaker, empty flashlight hook, and blue chalk mark',
    people: [
      { name: 'Eli', role: 'Art club student', statement: 'I only crossed the science wing on my way outside. I did not touch the breaker cabinet.' },
      { name: 'Mei', role: 'Science club student', statement: 'I was inside the lab when the lights failed, so I used my phone light to leave.' },
      { name: 'Mrs. Ford', role: 'Custodian', statement: 'The flashlight was on its hook at 6:10, and every breaker was up.' },
    ],
    scene: 'The science wing lost power for seven minutes, and its emergency flashlight disappeared. One breaker had been deliberately pushed down.',
    clues: [
      'A battery clock stopped at the exact moment of the outage: 6:18 PM.',
      'The breaker handle carries a fresh streak of blue chalk dust.',
      'Eli had been drawing stage scenery with blue chalk and still had dust on both hands.',
      'The missing flashlight was later found inside the art club’s supply cart.',
      'The science lab’s internal camera shows Mei inside when the corridor went dark.',
    ],
    question: 'Who most likely lowered the breaker and took the flashlight?',
    answers: ['Eli', 'Mei', 'Mrs. Ford', 'An unknown visitor'], correctAnswer: 0,
    explanation: 'Blue chalk connects Eli to the breaker, and the flashlight’s location in the art cart supports the same conclusion.',
  },
  {
    title: 'The Missing Berry Tart', location: 'Community Bake-Sale Kitchen', time: 'Saturday, 9:10–9:30 AM',
    image: '/images/detective/missing-tart.png',
    imageAlt: 'Kitchen with an empty tart rack, pawprints, a glove mark in flour, and a blue delivery bag',
    people: [
      { name: 'Leah', role: 'Baker', statement: 'I left the berry tart cooling on the center rack at 9:10.' },
      { name: 'Ben', role: 'Volunteer', statement: 'A small dog ran through the open door, but it never reached the high table.' },
      { name: 'Kai', role: 'Bicycle courier', statement: 'I collected only a box of cookies. My insulated bag was empty before I left.' },
    ],
    scene: 'The bake sale’s main berry tart disappeared from a high cooling rack. Pawprints near the door make the family dog look suspicious at first.',
    clues: [
      'The small pawprints stop two meters before the table and never circle the cooling rack.',
      'A narrow bicycle-glove print appears in spilled flour beside the rack.',
      'Kai wore narrow cycling gloves while collecting the cookie order.',
      'A fresh berry smear is visible inside the open blue insulated bag.',
      'The cookie box was small enough to carry without using the insulated bag.',
    ],
    question: 'Who most likely placed the tart inside the delivery bag?',
    answers: ['Leah', 'Ben', 'Kai', 'The dog'], correctAnswer: 2,
    explanation: 'The dog tracks are a distraction. The glove print and berry smear directly connect Kai’s equipment to the missing tart.',
  },
];
