import { extraDetectiveCases } from './detectiveCasesExtra';
import type { DetectiveCase } from './detectiveTypes';

const originalDetectiveCases: DetectiveCase[] = [
  {
    title: 'The Missing Trophy',
    location: 'West Hall, Northbridge School',
    time: 'Tuesday, 12:20–12:45 PM',
    image: '/images/detective/missing-trophy.png',
    imageAlt: 'School trophy cabinet with an empty stand, damp footprints, and grass on the floor',
    people: [
      { name: 'Coach Dana', role: 'Key holder', statement: 'Practice ended at 12:30. I crossed the field and went through West Hall, but I did not open the cabinet.' },
      { name: 'Mr. Reed', role: 'Janitor', statement: 'I spent the whole lunch break repairing the science-building sink. The maintenance camera should show me there.' },
      { name: 'Ivy', role: 'Student witness', statement: 'I saw the coach enter from the field. Their shoes were wet and covered with bits of grass.' },
    ],
    scene: 'The championship trophy vanished while most students were at lunch. At 12:45, the principal found the display cabinet closed and locked. Nothing else in the hallway had been disturbed.',
    clues: [
      'The cabinet glass and lock have no damage, so a real key was used.',
      'Only the coach and the janitor signed for cabinet keys that morning.',
      'A maintenance camera recorded the janitor fixing a sink across campus from 12:15 until 12:50.',
      'Several damp shoeprints lead from the sports-field entrance toward the cabinet.',
      'Fresh blades of field grass lie beside the empty trophy stand. The coach came directly from practice.',
    ],
    question: 'Who most likely opened the display case?',
    answers: ['The coach', 'The janitor', 'A student', 'The principal'],
    correctAnswer: 0,
    explanation: 'The case was opened with a key. The janitor had a confirmed alibi, while the grass connects the coach to the scene.',
  },
  {
    title: 'The Library Note',
    location: 'Riverside School Library',
    time: 'Friday, 3:45–4:10 PM',
    image: '/images/detective/library-note.png',
    imageAlt: 'Returned library books with a folded note and a wall clock showing four o’clock',
    people: [
      { name: 'Mira', role: 'Student', statement: 'I returned my books at 3:45 and left before the librarian checked the empty cart.' },
      { name: 'Leo', role: 'Student', statement: 'I only went inside to look at the clock. I did stand beside the returns desk for a minute.' },
      { name: 'Ana', role: 'Student', statement: 'My bus arrived at 4:10. The librarian and I entered the building together.' },
    ],
    scene: 'The librarian found an unsigned note tucked into the top book on the returns cart. The cart was empty at 3:45 PM and was checked again at 4:10 PM.',
    clues: [
      'Mira returned three books at 3:45 PM, before the empty cart was checked, and left immediately.',
      'Leo entered at 3:55 PM, stayed near the returns desk, and borrowed no books.',
      'A student heard the wall clock strike 4:00 while Leo was still inside.',
      'Ana’s bus arrived at 4:10 PM, and she entered with the librarian.',
      'The entrance camera shows nobody else entering between 3:50 and 4:05 PM.',
    ],
    question: 'Who could have placed the note at 4:00 PM?',
    answers: ['Mira', 'Leo', 'Ana', 'Nobody'],
    correctAnswer: 1,
    explanation: 'Only Leo was inside the library at 4:00 PM and close enough to reach the returns desk.',
  },
  {
    title: 'The Broken Greenhouse',
    location: 'School Garden Greenhouse',
    time: 'Wednesday, about 6:05 PM',
    image: '/images/detective/broken-greenhouse.png',
    imageAlt: 'Greenhouse with a broken window, a stone inside, and muddy footprints on the outside path',
    people: [
      { name: 'Sam', role: 'Garden club member', statement: 'I was inside watering the seedlings. I heard the crash from the opposite end of the greenhouse.' },
      { name: 'Nora', role: 'Garden club member', statement: 'I stayed at the paved gate. I never walked down the muddy path beside the broken window.' },
      { name: 'Ms. Chen', role: 'Club leader', statement: 'Sam had the watering can. Nora left through the gate a few minutes before I heard the glass break.' },
    ],
    scene: 'Minutes after the garden club ended, a side window shattered. Sam and Nora both said they were nearby, but each described being in a different place when the glass broke.',
    clues: [
      'A heavy garden stone lies inside directly below the hole, proving it was thrown from outside.',
      'Sam says he was watering seedlings inside at the far end of the greenhouse.',
      'A wet watering can and a newly watered row of seedlings support Sam’s account.',
      'Nora says she remained beside the paved gate and never walked along the muddy side path.',
      'Fresh mud matching that path is packed into Nora’s shoe treads, and prints lead close to the broken pane.',
    ],
    question: 'Whose story is most suspicious?',
    answers: ['Sam’s', 'Nora’s', 'Both stories', 'Neither story'],
    correctAnswer: 1,
    explanation: 'The window was struck from outside, and the soil places Nora on the path beside it rather than only at the gate.',
  },
  {
    title: 'The Cold Cup',
    location: 'Corner Cup Café',
    time: 'Saturday, 2:42 PM',
    image: '/images/detective/cold-cup.png',
    imageAlt: 'Cold hot chocolate beside a receipt marked 2:10 PM and a clock showing 2:42 PM',
    people: [
      { name: 'Jordan', role: 'Guest', statement: 'This drink arrived a minute ago and was already cold. I want a refund.' },
      { name: 'Elena', role: 'Server', statement: 'I delivered it just after 2:10. The guest was busy on the phone and did not touch it.' },
      { name: 'Marco', role: 'Barista', statement: 'I made only one hot chocolate after 2 PM. The register recorded it at 2:10.' },
    ],
    scene: 'A guest asks for a refund, insisting the hot chocolate arrived only one minute ago and was served cold. The server says the drink sat untouched for more than half an hour.',
    clues: [
      'The café uses thick ceramic cups that keep a fresh drink warm for at least twenty minutes.',
      'There is no steam, and a clean chocolate ring has dried just above the current liquid level.',
      'The order receipt beside the cup records a preparation time of 2:10 PM.',
      'The café wall clock and the server’s watch both show 2:42 PM.',
      'No second hot-chocolate order appears on the register after 2:10 PM.',
    ],
    question: 'What does the evidence show?',
    answers: ['The cup is faulty', 'The clock is wrong', 'The drink was served long ago', 'The server used ice'],
    correctAnswer: 2,
    explanation: 'The receipt proves the drink was prepared 32 minutes earlier, which explains why it is cold.',
  },
  {
    title: 'The Password Mystery',
    location: 'Room 204 Computer Station',
    time: 'Monday, 4:15 PM',
    image: '/images/detective/password-mystery.png',
    imageAlt: 'Locked classroom computer beside a rabbit figure and two equal groups of nine counters',
    people: [
      { name: 'Ms. Patel', role: 'Teacher', statement: 'The password begins with our class pet’s name and ends with two digits.' },
      { name: 'Owen', role: 'Class monitor', statement: 'Our rabbit is named Comet. The digits come from splitting the class into two equal teams.' },
      { name: 'Lina', role: 'Quiz captain', statement: 'All 18 students attended. My team and the other team had the same number of students.' },
    ],
    scene: 'The class computer was found on its login screen after somebody had used it. The teacher never wrote the password down, but left a set of memory clues for the class.',
    clues: [
      'The password is the class pet’s name followed by exactly two digits.',
      'The rabbit-shaped reminder points to the class rabbit, whose name is Comet.',
      'The two digits equal the number of students in each of two equal quiz teams.',
      'The attendance sheet lists 18 students, and nobody was absent.',
      'The counters in the photo form two equal groups of nine, confirming the calculation.',
    ],
    question: 'Which password fits every clue?',
    answers: ['Comet18', 'Rabbit09', 'Comet99', 'Comet09'],
    correctAnswer: 3,
    explanation: 'The pet’s name is Comet, and 18 students split into two equal teams gives 9: Comet09.',
  },
];

export const detectiveCases = [...originalDetectiveCases, ...extraDetectiveCases];
